from pathlib import Path
import hashlib

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw"
REFERENCE = ROOT / "data" / "reference" / "source_registry.csv"
OUTDIR = ROOT / "data" / "interim"
OUTPUT = OUTDIR / "source_registry_resolved.csv"
DOC = ROOT / "docs" / "DATA_SOURCES.md"


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def build_registry() -> pd.DataFrame:
    df = pd.read_csv(REFERENCE, dtype=str).fillna("")
    if df["filename"].duplicated().any():
        raise AssertionError("Source registry filenames must be unique")
    rows = []
    for r in df.itertuples(index=False):
        path = RAW / r.filename
        if not path.is_file():
            raise FileNotFoundError(f"Registered raw source is missing: {r.filename}")
        actual = digest(path)
        if actual != r.expected_sha256:
            raise AssertionError(
                f"Raw source checksum mismatch for {r.filename}: expected {r.expected_sha256}, got {actual}"
            )
        row = r._asdict()
        row.update({"bytes": path.stat().st_size, "actual_sha256": actual, "status": "verified"})
        rows.append(row)
    return pd.DataFrame(rows)


def render_markdown(df: pd.DataFrame) -> str:
    lines = [
        "# Data sources",
        "",
        "Generated by `scripts/data/build_source_registry.py` from `data/reference/source_registry.csv` and the exact files in `data/raw/`.",
        "",
        "Raw files are immutable project snapshots. SHA-256 is checked before S1–S3 runs.",
        "",
        "| File | Institution | Snapshot | Release / coverage | Role | SHA-256 | Notes |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in df.itertuples(index=False):
        notes = str(r.notes).replace("|", "\\|")
        role = str(r.project_role).replace("|", "\\|")
        lines.append(
            f"| `{r.filename}` | {r.institution} | {r.snapshot_date} | {r.release_or_coverage} | {role} | `{r.actual_sha256}` | {notes} |"
        )
    lines.extend(
        [
            "",
            "## Interpretation boundaries",
            "",
            "- DataTur coverage is hotel-center context; absence is not low tourism demand.",
            "- INAH visitors are attraction/site visits, not municipal tourism totals.",
            "- DENUE variables are service/infrastructure proxies, not ecological carrying capacity.",
            "- `veracruz_pueblos_magicos_2026-10-06.html` preserves the CAPTCHA challenge returned to Codespaces. `veracruz_pueblos_magicos_2026-10-06_manual.html` is the browser-saved real SECTUR page and is the preferred local parser input; the products-page menu remains a fallback.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    DOC.parent.mkdir(parents=True, exist_ok=True)
    out = build_registry()
    out.to_csv(OUTPUT, index=False)
    DOC.write_text(render_markdown(out), encoding="utf-8")
    print(f"Verified {len(out):,} raw sources -> {OUTPUT.relative_to(ROOT)}")
    print(f"Wrote -> {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
