from pathlib import Path
import hashlib

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
RAW = ROOT / "data" / "raw"
REFERENCE = ROOT / "data" / "reference" / "source_registry.csv"
OUTDIR = ROOT / "data" / "interim"
OUTPUT = OUTDIR / "source_registry_resolved.csv"
DOC = ROOT / "docs" / "DATA_SOURCES.md"


def digest(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def build_registry() -> pd.DataFrame:
    df = pd.read_csv(REFERENCE, dtype=str).fillna("")
    if "storage_mode" not in df.columns:
        df["storage_mode"] = "local_raw"
    if df["filename"].duplicated().any():
        raise AssertionError("Source registry filenames must be unique")

    allowed = {"local_raw", "remote_fixed"}
    invalid = set(df["storage_mode"]) - allowed
    if invalid:
        raise AssertionError(f"Unsupported source storage_mode values: {sorted(invalid)}")

    rows = []
    for r in df.itertuples(index=False):
        row = r._asdict()
        if r.storage_mode == "local_raw":
            path = RAW / r.filename
            if not path.is_file():
                raise FileNotFoundError(f"Registered raw source is missing: {r.filename}")
            if not r.expected_sha256:
                raise AssertionError(f"Local raw source lacks expected SHA-256: {r.filename}")
            actual = digest(path)
            if actual != r.expected_sha256:
                raise AssertionError(
                    f"Raw source checksum mismatch for {r.filename}: expected {r.expected_sha256}, got {actual}"
                )
            row.update({"bytes": path.stat().st_size, "actual_sha256": actual, "status": "verified"})
        else:
            if not str(r.source_url).startswith("https://"):
                raise AssertionError(f"Remote fixed source requires an https URL: {r.filename}")
            row.update({"bytes": "", "actual_sha256": "", "status": "remote_fixed"})
        rows.append(row)
    return pd.DataFrame(rows)


def render_markdown(df: pd.DataFrame) -> str:
    local_n = int((df["storage_mode"] == "local_raw").sum())
    remote_n = int((df["storage_mode"] == "remote_fixed").sum())
    lines = [
        "# Data sources",
        "",
        "Generated by `scripts/data/build_source_registry.py` from `data/reference/source_registry.csv`.",
        "",
        f"The registry contains {local_n} immutable local raw snapshots and {remote_n} exact fixed remote report(s). Local raw files are SHA-256 checked before S1-S3 runs. The normal analytical pipeline does not fetch network data.",
        "",
        "| Source | Mode | Institution | Snapshot / version | Release / coverage | Role | Verification | Notes |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in df.itertuples(index=False):
        notes = str(r.notes).replace("|", "\\|")
        role = str(r.project_role).replace("|", "\\|")
        if r.storage_mode == "local_raw":
            verification = f"SHA-256 `{r.actual_sha256}`"
            source_label = f"`{r.filename}`"
        else:
            verification = "Fixed HTTPS report; structured facts version-controlled in reference data"
            source_label = f"`{r.filename}` (remote)"
        lines.append(
            f"| {source_label} | {r.storage_mode} | {r.institution} | {r.snapshot_date} | {r.release_or_coverage} | {role} | {verification} | {notes} |"
        )
    lines.extend(
        [
            "",
            "## Interpretation boundaries",
            "",
            "- DataTur coverage is hotel-center context; absence is not low tourism demand.",
            "- INAH visitors are attraction/site visits, not municipal tourism totals.",
            "- DENUE variables are service/infrastructure proxies, not ecological carrying capacity.",
            "- The origin-market report describes foreign air-entry events to Mexico by country of residence. It is not evidence that those travelers visited Veracruz.",
            "- `veracruz_pueblos_magicos_2026-10-06.html` preserves the CAPTCHA challenge returned to Codespaces. `veracruz_pueblos_magicos_2026-10-06_manual.html` is the browser-saved real SECTUR page and is the preferred local parser input; the products-page menu remains a fallback.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    DOC.parent.mkdir(parents=True, exist_ok=True)
    out = build_registry()
    out.to_csv(OUTPUT, index=False)
    DOC.write_text(render_markdown(out), encoding="utf-8")
    local_n = int((out["status"] == "verified").sum())
    remote_n = int((out["status"] == "remote_fixed").sum())
    print(f"Verified {local_n:,} local raw sources; registered {remote_n:,} fixed remote report(s) -> {OUTPUT.relative_to(ROOT)}")
    print(f"Wrote -> {DOC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
